name = "adtunnel"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "35.219.50.99:443"
UUID = "08e454f6-de0a-4d49-826c-910572785656"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
